#here are the stories that the for statement will iterate through!
#key: _n_ is noun, _v_ is verb, and _a_ is adjective
import random

tortAndHare = "\n~THE TORTOISE AND THE HARE~\nOne day a hare was bragging about how _a_  he could run. He bragged and bragged and even _pv_  at the tortoise, who was so _a_ . The tortoise stretched out his long _n_  and challenged the hare to a _n_ , which, of course, made the hare _v_ .\n‘My, my, what a _n_ !’ thought the hare.\n‘A race, indeed, a _n_ . Oh! what fun! My, my! a _n_ , of course, Mr. Tortoise, we shall _v_ !’ said the hare.\nThe forest animals met and _pv_  out the course. The race began, and the hare, being such a _a_  runner, soon left the tortoise far behind. About halfway through the course, it occurred to the hare that he had plenty of time to _v_  the _a_  trodden tortoise.\n‘Oh, my!’ thought the hare, ‘I have plenty of time to _v_  in the _n_  here.’\nAnd so he did.\nAfter the hare finished playing, he decided that he had time to take a _a_  nap.\n‘I have plenty of time to beat that tortoise,’ he thought. And he cuddled up against a tree and _pv_  .\nThe tortoise, in the meantime, continued to _v_  on, albeit, ever so _av_ . He never _pv_ , but took one _a_  step after another.\nThe hare _av_  _pv_  from his nap. ‘Time to get going,’ he thought. And off he went faster than he had ever _pv_  before! He dashed as _av_  as anyone ever could up to the finish line, where he met the tortoise, who was _av_  awaiting his arrival. _a_  and _a_  won the race!\n"

redRidingHood = "\n~LITTLE RED RIDING HOOD~\nLittle Red Riding Hood lived in a _n_  with her _n_ . One day Little Red Riding Hood went to visit her _n_ . She had a nice _n_  in her basket.\nOn her way Little Red Riding Hood met a wolf.\n‘Hello!’ said the wolf. ‘Where are you going?’\n‘I’m going to see my _n_ . She lives in a _n_  behind those trees.’\nThe wolf ran to Granny’s house and _pv_  Granny up. He got into Granny’s bed. A little later, Little Red Riding Hood reached the house. She _pv_  at the wolf.\n‘Granny, what _a_  _n_  you have!’\n‘All the better to _v_  you with!’ said the wolf.\n‘Granny, what _a_  _n_  you have!’\n‘All the better to _v_  you with!’ said the wolf.\n‘Granny, what a _a_  _n_  you have!’\n‘All the better to _v_  you with!’ said the wolf.\n‘Granny, what big _n_  you have!’\n‘All the better to _v_  you with!’ shouted the wolf.\nA _n_  was in the wood. He heard a loud _n_  and ran to the house. The woodcutter hit the wolf over the head. The wolf opened his mouth _a_  and _pv_  and Granny jumped out. \nThe wolf _pv_  away and Little Red Riding Hood never saw him again.\n"

grasshopper_ants = "\n~THE GRASSHOPPER AND THE ANTS~\nOne _a_  day in late autumn a _n_  of Ants were bustling about\nin the warm sunshine, drying out the _n_  they had stored up\nDuring the summer, when a _a_  Grasshopper, his _n_  under\nhis arm, came up and _av_  begged for a bite to eat.\n'What!'  _pv_  the Ants in surprise,\n'haven't you stored anything away for the winter?' What in the _n_  were you _v_   all last summer?\nI didn't have time to store up any _n_  , _pv_  the Grasshopper;\nI was so busy making _n_  that before I knew it the summer was gone.\nThe Ants shrugged their shoulders in disgust. _v_  music, were you? they cried. Very well; now _v_ !\nAnd they turned their backs on the Grasshopper and went on with their work.’\nThere's a time for _n_  and a time for _n_ .\n"


tales = [redRidingHood, tortAndHare, grasshopper_ants]
def ran_story():
  return random.choice(tales)
# this will choose a random story from the list, which we will imported into main.py if the user picks option #4